services:
    _defaults:
        public: true

    coreshop.store.theme_resolver:
        alias: coreshop.theme.resolver

    coreshop.store.theme_helper:
        alias: coreshop.theme.helper

    coreshop.theme.store_resolver:
        class: CoreShop\Bundle\StoreBundle\Theme\StoreThemeResolver
        decorates: 'coreshop.theme.resolver'
        arguments:
            - '@liip_theme.active_theme'
            - '@coreshop.context.store'
            - '@coreshop.repository.store'